displayName=Gielinor Explored
author=Tim
description=Reveals your path through Gielinor
tags=map, fogofwar, path, minimap, worldmap, explore, travel, discovery
version=1.0.0
plugins=com.gielinorexplored
build=standard